name: Andrew's Articles
description: Programming and Tech
meta_description: "Andrew's Articles"
disqus_shortname: "andrewdolby"
markdown: kramdown
highlighter: rouge
logo: false
paginate: 20
baseurl: /articles
domain_name: 'https://andrewdolby.com'
google_analytics: 'UA-87952975-1'
gems: [jekyll-paginate]
permalink: /:year/:title

# Details for the RSS feed generator
url: 'https://andrewdolby.com'
author: 'Andrew Dolby'
